### ISSUE TITLE
sandbox

### ISSUE THREAD

**Issue by hlb-schmidt** [ratepay/shopware5-module#17]
wo finden wir ratepay sandbox?
und überhaupt, ratepay entwickler dokumentation?

**Comment by rommelfreddy** [comment]
die Entwickler Doku findest du hier:
https://ratepay.gitbook.io/docs/
Die Dokumentation für das Shopware Plugin findest du hier:
https://ratepay.gitbook.io/shopware/

Bei weiteren Fragen wende dich bitte an deinen Sales Manager ✌️
