### ISSUE TITLE
Deprecated PHP methods used

### ISSUE THREAD

**Issue by philippuhr** [ratepay/shopware5-module#41]
**HowTo**
When the shopping cart is confirmed and installment payment is selected, two warnings are displayed. https://www.shopwaredemo.de/checkout/confirm

**Errors**
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; PiRatepayRateCalc has a deprecated constructor in ../Plugins/Community/Frontend/RpayRatePay/Views/responsive/frontend/installment/php/PiRatepayRateCalc.php on line 19

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; PiRatepayRateCalcBase has a deprecated constructor in ../Plugins/Community/Frontend/RpayRatePay/Views/responsive/frontend/installment/php/PiRatepayRateCalcBase.php on line 15

**Example**
The name of a function can not be equal to the name of a class.
`class PiRatepayRateCalc extends PiRatepayRateCalcBase{}`
`public function PiRatepayRateCalc() { parent::PiRatepayRateCalcBase(); }`

**Comment by rommelfreddy** [comment]
hello @philippuhr,
all files in the folder "php" in the module will me removed in a further release.
so this "issue" will not occur any more.
please be patience.
