### ISSUE TITLE
Useless broken payment & order status

### ISSUE THREAD

**Issue by larsbo** [ratepay/shopware5-module#59]
This lines add empty order and payment status (because the title is missing) that never seems to be used:
 
https://github.com/ratepay/shopware5-module/blob/e25c229b3350afcbd131420b70c6b58e6951c0c1/Bootstrapping/DeliveryStatusesSetup.php#L17
https://github.com/ratepay/shopware5-module/blob/e25c229b3350afcbd131420b70c6b58e6951c0c1/Bootstrapping/DeliveryStatusesSetup.php#L24
https://github.com/ratepay/shopware5-module/blob/e25c229b3350afcbd131420b70c6b58e6951c0c1/Bootstrapping/PaymentStatusesSetup.php#L17

**Comment by rommelfreddy** [comment]
Hey Martin!
this issue is related to the internal ticket RATEPLUG-73.
please also have a look to the PR https://github.com/ratepay/shopware5-module/pull/60

**Comment by MartinKuhl** [comment]
Closed with new release version
